# Generated by Django 4.1 on 2022-09-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_travel_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfare',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='shop_travel_work.location'),
            preserve_default=False,
        ),
    ]
