# Generated by Django 4.1 on 2022-09-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_travel_work', '0002_localfare_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfare',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localfares', to='shop_travel_work.location'),
        ),
    ]
