# Generated by Django 4.1 on 2022-09-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_travel_work', '0003_alter_localfare_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password_digest', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='localfare',
            name='recommend',
            field=models.IntegerField(choices=[(-1, 'Stay Away'), (0, 'Neutral'), (1, 'Recommend')]),
        ),
        migrations.CreateModel(
            name='LocationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localposts', to='shop_travel_work.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationposts', to='shop_travel_work.user')),
            ],
        ),
        migrations.CreateModel(
            name='LocalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('store', models.CharField(max_length=100)),
                ('store_url', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localitems', to='shop_travel_work.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localitems', to='shop_travel_work.user')),
            ],
        ),
        migrations.AddField(
            model_name='localfare',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localfares', to='shop_travel_work.user'),
            preserve_default=False,
        ),
    ]
